server:
  port: 8082

spring:
  application:
    name: nx-auto-ms-shop
#  devtools:
#    livereload:
#      port: 35731
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: health,info
