server:
  port: 8082

spring:
  application:
    name: nx-auto-ms-shop

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  application:
    name: nx-auto-ms-shop
  consumer:
    timeout: 5000
