spring:
  application:
    name: nx-auto-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://nx-auto-ms-auth
          predicates:
            - Path=/api/v1/auth/**
        - id: customer
          uri: lb://nx-auto-ms-customer
          predicates:
          - Path=/api/v1/customer/**
        - id: shop
          uri: lb://nx-auto-ms-shop
          predicates:
          - Path=/api/v1/shop/**

#  main:
#    web-application-type: reactive
server:
  port: 8080
