server:
  port: 8081

spring:
  application:
    name: nx-auto-ms-customer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  application:
    name: nx-auto-ms-customer
  consumer:
    timeout: 5000
